//
// File generated by HDevelop for HALCON/.NET (C#) Version 18.11.1.1
// Non-ASCII strings in this file are encoded in UTF-8.
// 
// Please note that non-ASCII characters in string constants are exported
// as octal codes in order to guarantee that the strings are correctly
// created on all systems, independent on any compiler settings.
// 
// Source files with different encoding should not be mixed in one project.
//


using System;
using HalconDotNet;

public partial class HDevelopExport
{
  public void image_class_mia (HObject ho_Image, HTuple hv_WindowHandle, out HTuple hv_DecodedDataStrings)
  {




    // Local iconic variables 

    HObject ho_SymbolXLDs;

    // Local control variables 

    HTuple hv_DataCodeHandle = new HTuple(), hv_ResultHandles = new HTuple();
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_SymbolXLDs);
    hv_DecodedDataStrings = new HTuple();
    //* INIT BARCODE
    hv_DataCodeHandle.Dispose();
    HOperatorSet.CreateDataCode2dModel("Data Matrix ECC 200", new HTuple(), new HTuple(), 
        out hv_DataCodeHandle);
    ho_SymbolXLDs.Dispose();hv_ResultHandles.Dispose();hv_DecodedDataStrings.Dispose();
    HOperatorSet.FindDataCode2d(ho_Image, out ho_SymbolXLDs, hv_DataCodeHandle, "stop_after_result_num", 
        3, out hv_ResultHandles, out hv_DecodedDataStrings);
    //image_display_datacode (SymbolXLDs, ResultHandles, WindowHandle, DecodedDataStrings, DataCodeHandle)
    ho_SymbolXLDs.Dispose();

    hv_DataCodeHandle.Dispose();
    hv_ResultHandles.Dispose();

    return;
  }

}
