//
// File generated by HDevelop for HALCON/.NET (C#) Version 18.11.1.1
// Non-ASCII strings in this file are encoded in UTF-8.
// 
// Please note that non-ASCII characters in string constants are exported
// as octal codes in order to guarantee that the strings are correctly
// created on all systems, independent on any compiler settings.
// 
// Source files with different encoding should not be mixed in one project.
//


using System;
using HalconDotNet;

public partial class HDevelopExport
{
  public void image_get_bar (HObject ho_Image, out HObject ho_SymbolRegions, HTuple hv_BarCodeHandle, 
      out HTuple hv_DecodedDataStrings, out HTuple hv_someitem)
  {




    // Local iconic variables 

    // Local control variables 

    HTuple hv_CodeTypes = new HTuple(), hv_Width = new HTuple();
    HTuple hv_Height = new HTuple();
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_SymbolRegions);
    hv_DecodedDataStrings = new HTuple();
    hv_someitem = new HTuple();
    //
    //Use autodiscrimination to decode any of the bar code types
    //supported by HALCON (except PharmaCode) or determine the bar
    //code type of unknown bar codes
    //
    hv_CodeTypes.Dispose();
    hv_CodeTypes = "Code 128";
    hv_CodeTypes.Dispose();
    hv_CodeTypes = "auto";
    //
    //Set display defaults
    hv_Width.Dispose();hv_Height.Dispose();
    HOperatorSet.GetImageSize(ho_Image, out hv_Width, out hv_Height);


    //
    //Find and decode bar codes. Measure the time needed.
    ho_SymbolRegions.Dispose();hv_DecodedDataStrings.Dispose();
    HOperatorSet.FindBarCode(ho_Image, out ho_SymbolRegions, hv_BarCodeHandle, hv_CodeTypes, 
        out hv_DecodedDataStrings);
    //get_bar_code_result (BarCodeHandle, 'all', 'someitem', someitem)

    hv_CodeTypes.Dispose();
    hv_Width.Dispose();
    hv_Height.Dispose();

    return;
  }

}
