//
// File generated by HDevelop for HALCON/.NET (C#) Version 18.11.1.1
// Non-ASCII strings in this file are encoded in UTF-8.
// 
// Please note that non-ASCII characters in string constants are exported
// as octal codes in order to guarantee that the strings are correctly
// created on all systems, independent on any compiler settings.
// 
// Source files with different encoding should not be mixed in one project.
//


using System;
using HalconDotNet;

public partial class HDevelopExport
{
  public void region_get_corner (HObject ho_Image, HObject ho_Rectangle, HTuple hv_WindowHandle, 
      out HTuple hv_Rows, out HTuple hv_Cols)
  {
  }



}
