//
// File generated by HDevelop for HALCON/.NET (C#) Version 18.11.1.1
// Non-ASCII strings in this file are encoded in UTF-8.
// 
// Please note that non-ASCII characters in string constants are exported
// as octal codes in order to guarantee that the strings are correctly
// created on all systems, independent on any compiler settings.
// 
// Source files with different encoding should not be mixed in one project.
//
//  This file is intended to be used with the HDevelopTemplate or
//  HDevelopTemplateWPF projects located under %HALCONEXAMPLES%\c#

using System;
using System.Windows.Forms;
using HalconDotNet;
//using static HDevelopExport;

public partial class HDevelopExport
//public partial class HalMiaUsed
{

    public HTuple hv_ExpDefaultWinHandle;
    public HTuple hv_ExpImageRawWinHandle;
    HTuple hv_AcqHandle = new HTuple();

    public void HDevelopStop()
    {
        MessageBox.Show("Press button to continue", "Program stop");
    }



    //public void InitHalconMiaUsed()
    public void InitHalcon()
    {
        // Default settings used in HDevelop
        HOperatorSet.SetSystem("width", 512);
        HOperatorSet.SetSystem("height", 512);
    }

    public void RunHalconMiaUsed(HTuple Window, HTuple ImageRawWin)
    {
        hv_ExpDefaultWinHandle = Window;
        hv_ExpImageRawWinHandle = ImageRawWin;
        actionMiaUsed();
    }
    public void StopHalcon()
    {
        HOperatorSet.CloseFramegrabber(hv_AcqHandle);
    }

}

